In [1]:
import numpy as np
import laserhockey.hockey_env as h_env
import gymnasium as gym
from gymnasium import spaces
import os
import pickle
import torch
from SACAgent import SAC
from param_save import save_param, load_param
import matplotlib.pyplot as plt

In [2]:
def play(env,agent,n_episodes =100,gamma=1,max_Step=2000,LH=False, render=False):
    rewards = []
    timestep = 0

    #player1 = agent
    opponent = h_env.BasicOpponent(weak=False)
    #max_Step=2000
    for ep in range(1, n_episodes+1):
        #print(ep)
        
        #env.reset()
        ob, _info = env.reset()
        obs_agent2 = env.obs_agent_two()

        total_reward=0
        
        for t in range(max_Step):
            
            timestep += 1
            done = False
            #a,_ =  player1.act(ob,True)
            #a2 = player2.act(obs_agent2)
            a,_ = agent.act(ob,True)

            ob2 = env.obs_agent_two()
            a2 = opponent.act(ob2,True)

            (ob_new, reward, done, trunc, _info) = env.step(np.hstack([a,a2]))
            total_reward +=  gamma ** t * reward
            ob=ob_new
            if done or trunc: 
                break  
            if render:
                clear_output(wait=True)
                plt.imshow(env.render())
                plt.show()
            if LH:
                env.render(mode="human")
        #print("episode ",ep,total_reward)      
        rewards.append(total_reward)
    if render or LH:
        plt.close()
        env.close()
    
    print(f'Mean reward: {np.mean(rewards)}')
    return rewards

In [3]:
env1 = h_env.HockeyEnv_BasicOpponent(mode=h_env.HockeyEnv.TRAIN_DEFENSE, weak_opponent=False)
env2 = h_env.HockeyEnv(mode=h_env.HockeyEnv.TRAIN_DEFENSE)

In [4]:
agent = SAC(env1.observation_space,env1.action_space)


In [5]:
load_param(agent,"param_new",str(10000))

In [14]:
env1 = h_env.HockeyEnv_BasicOpponent(mode=h_env.HockeyEnv.TRAIN_DEFENSE, weak_opponent=False)
play(env1,agent,5,max_Step=100,LH=True)

[-3.77803183  0.94878697  0.08387923] [377.8031826   94.8786974    8.38792295] [False False False]
[-3.77801323 -1.1895504   0.24353876] [3.77801323e+02 9.50591429e-01 2.77283590e-01] [False False  True]
[-3.77776146 -1.18562412  0.30994418] [3.77776146e+02 2.43678949e+00 1.25697840e-01] [False False  True]
[-3.77704668 -1.16220307  0.43178062] [3.77704668e+02 7.59952409e-01 1.42320785e-01] [False False  True]
[-3.77529716 -1.12913537  0.44585682] [3.77529716e+02 5.23969086e-01 1.04848910e-01] [False False  True]
[-3.77264786 -1.08850121  0.42630402] [3.77264786e+02 4.30176631e-01 9.89913111e-02] [False False  True]
[-3.76932335 -1.04262853  0.36608086] [3.76932335e+02 3.78367878e-01 8.92879066e-02] [False False  True]
[3.01164742 1.20572919 0.42404087] [3.01164742e+02 4.17101060e-01 1.21428319e-01] [False False  True]
[2.30054731 8.03986563 0.39096088] [2.30054731e+02 1.64393396e+01 9.44851501e-02] [False False  True]
[-3.75620794  0.7689476   0.357233  ] [3.75620794e+02 8.07767453e-0

[8.859205049143222,
 8.434453688010166,
 8.722844293459238,
 7.640730118604159,
 8.219806485025487]

In [15]:
env2 = h_env.HockeyEnv_BasicOpponent(mode=h_env.HockeyEnv.NORMAL, weak_opponent=False)
play(env2,agent,5,max_Step=150,LH=True)

[ 1.35329409 -0.1169467   0.54794708] [135.32940865  11.69466972  54.7947079 ] [False False False]
[ 1.31615801 -0.11330223  0.52739154] [0.70304999 0.2662642  0.25350944] [False False  True]
[ 1.2462122  -0.10691929  0.60828583] [0.35125043 0.13299641 0.14953275] [False False  True]
[ 1.14793272 -0.09865618  0.60997204] [0.22703438 0.08802963 0.10207104] [False  True  True]
[ 1.02410717 -0.10571527  0.5839123 ] [0.15967607 0.32798433 0.099376  ] [False False  True]
[ 0.87712975 -0.10440254  0.5129411 ] [0.11487736 0.15290701 0.09137547] [False False  True]
[ 0.70857639 -0.09453392  0.43829023] [0.08112024 0.09431553 0.08947278] [ True  True  True]
[ 0.52013798 -0.09647894  0.38348309] [0.05348754 0.31058053 0.09175185] [ True False  True]
[-1.51185036  0.03084135  0.3394222 ] [0.16526384 0.04054004 0.12773689] [False  True  True]
[-1.63041353  0.02598238  0.2777577 ] [0.25586265 0.17463901 0.08354582] [False False  True]
[-1.70003605  0.02092648  0.22057271] [0.4388401  0.09033199 0.0

[9.525502129767048,
 9.054369114016849,
 9.361633137205045,
 9.04256290919417,
 9.53200004316332]